"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _match_score from './match-score.bones.json'
import _skill_gaps from './skill-gaps.bones.json'
import _suggestions from './suggestions.bones.json'
import _insights_panel from './insights-panel.bones.json'
import _kanban_board from './kanban-board.bones.json'

registerBones({
  "match-score": _match_score,
  "skill-gaps": _skill_gaps,
  "suggestions": _suggestions,
  "insights-panel": _insights_panel,
  "kanban-board": _kanban_board,
})
